import assert from 'node:assert/strict';
globalThis.matchMedia = () => ({matches:false});
const { THREE, gridKey } = await import('../../src/core/shared.js');
const { generateFarm, generateIsland } = await import('../../src/world/generator.js');
const { createPhysics } = await import('../../src/physics/index.js');
const { findAttachmentPlacement, canReleaseIsland } = await import('../../src/world/islands/attachment-placement.js');
const physics = await createPhysics();
const farm = generateFarm(new THREE.Scene(), physics, 99173, 0, ()=>{}, {attachmentComplete:true});
physics.createVehicle('test',farm.spawn);
const incoming=generateIsland(12345,{radius:7});
console.time('placement');
const pose=findAttachmentPlacement(incoming.terrain,farm.terrain);
console.timeEnd('placement');
assert(pose);
assert(![...incoming.terrain.values()].some(t=>farm.terrain.has(gridKey(t.gx+pose.gx,t.gz+pose.gz))));
assert.deepEqual(pose,findAttachmentPlacement(incoming.terrain,farm.terrain));
for(const tile of incoming.terrain.values())for(const fixed of farm.terrain.values())assert(Math.hypot(Math.max(0,Math.abs(tile.gx+pose.gx-fixed.gx)-1),Math.max(0,Math.abs(tile.gz+pose.gz-fixed.gz)-1))>=4,'entire shore stops at least four tiles away');
console.log('PASS deterministic non-overlapping placement',pose.gx,pose.gz,pose.gaps.length);
const nodes=['island-0','island-1','a','b'].map(id=>({id,status:'attached'}));
const edge=(a,b)=>({status:'attached',from:{islandId:a},to:{islandId:b}});
const edges=[edge('island-0','island-1'),edge('island-0','a'),edge('a','b')];
assert(!canReleaseIsland('a',nodes,edges));assert(canReleaseIsland('b',nodes,edges));
assert(canReleaseIsland('a',nodes,[...edges,edge('b','island-0')]));
console.log('PASS leaf, articulation and alternate-route release graph');
const { createArchipelagoRuntime } = await import('../../src/world/archipelago/runtime.js');
const { validState } = await import('../../src/persistence/schema.js');
const initialTiles=farm.terrain.size, initialColliders=physics.staticColliders.length;
incoming.group.position.set(0,0,Math.max(...[...farm.terrain.values()].map(t=>t.z))-Math.min(...[...incoming.terrain.values()].map(t=>t.z))+6.5);incoming.status='drifting';incoming.side=-1;incoming.outerLane=0;
incoming.body=physics.addMovingIsland(incoming,incoming.group.position,false);
farm.group.add(incoming.group);farm.driftingIslands.active.push(incoming);
const shoreTile=[...incoming.terrain.values()].reduce((a,b)=>a.x>b.x?a:b);
const boundary={x:incoming.group.position.x+shoreTile.x+.5+12,y:0,z:incoming.group.position.z+shoreTile.z};
physics.placeVehicle('test',boundary,true);
assert(farm.attachments.available().includes(incoming),'shore at range boundary is selectable');
farm.attachments.select(incoming);assert(farm.attachments.state());
physics.placeVehicle('test',{...boundary,x:boundary.x+.1},true);
assert(!farm.attachments.available().includes(incoming),'outside range has no selectable outline');
assert(!farm.attachments.connect(),'cannot confirm after leaving range');
assert.equal(farm.attachments.state(),null,'leaving range clears selection and ghost');
farm.attachments.select(incoming);assert.equal(farm.attachments.state(),null,'direct selection cannot bypass range');
physics.placeVehicle('test',boundary,true);
physics.createVehicle('far',{x:500,y:0,z:500});physics.setActiveVehicle('far');
assert(!farm.attachments.available().includes(incoming),'range follows the active vehicle');
physics.setActiveVehicle('test');
assert(farm.attachments.available().includes(incoming));
console.log('PASS exact 12-tile active-vehicle range gates outline, selection, ghost and confirmation');

physics.placeVehicle('test',{x:0,y:0,z:Math.max(...[...farm.terrain.values()].map(t=>t.z))},true);
farm.attachments.select(incoming);
assert.equal(farm.attachments.state()?.action,'Connect');
assert(farm.attachments.connect());
const pendingWorld=createArchipelagoRuntime(farm).persistentState(0);
assert(pendingWorld.pendingAttachment);
const pendingPhysics=await createPhysics();
const pendingRestored=generateFarm(new THREE.Scene(),pendingPhysics,pendingWorld.seed,0,()=>{}, {attachmentComplete:true,savedWorld:pendingWorld});
assert.equal(pendingRestored.attachments.arrivalState().complete,false);
for(let i=0;i<92;i++)pendingRestored.attachments.update(.1);
assert.equal(pendingRestored.islands.length,3);
console.log('PASS reload during pull preserves the confirmed island and restarts its cinematic');
const start=incoming.group.position.clone();
farm.attachments.update(.1);
assert(incoming.group.position.distanceTo(start)>0);
assert.equal(farm.terrain.size,initialTiles);
for(let i=0;i<59;i++)farm.attachments.update(.1);
assert.equal(farm.terrain.size,initialTiles,'no playable terrain until bridge finishes');
for(let i=0;i<32;i++)farm.attachments.update(.1);
assert.equal(incoming.status,'attached');
assert.equal(farm.terrain.size,initialTiles+incoming.terrain.size);
assert(physics.staticColliders.length>initialColliders);
assert(incoming.links.every(link=>link.visual&&link.blocks.length));
assert(incoming.links.every(link=>link.gap.distance===4),'connected shore gap is four tiles');
console.log('PASS continuous pull → chain → bridge → normal terrain/collision');
const bridgeGap=incoming.links[0].gap;
physics.placeVehicle('test',{x:bridgeGap.from.x,y:bridgeGap.from.topY,z:bridgeGap.from.z},true);
const direction={x:(bridgeGap.to.x-bridgeGap.from.x)/bridgeGap.centerDistance,z:(bridgeGap.to.z-bridgeGap.from.z)/bridgeGap.centerDistance};
for(let i=0;i<90;i++){physics.drive(1/60,direction,1,false,false);physics.step(1/60);const p=physics.vehicleState('test');if(Math.hypot(p.x-bridgeGap.to.x,p.z-bridgeGap.to.z)<.7)break;}
const driven=physics.vehicleState('test');
assert(Math.hypot(driven.x-bridgeGap.to.x,driven.z-bridgeGap.to.z)<3,'vehicle crosses connection');
assert(driven.y>-.2,'bridge has continuous physical support');
console.log('PASS actual vehicle drives across the new bridge');

const farmland=[...incoming.worldTiles.values()].find(t=>!t.water&&!t.hasTree&&!t.reserved);
assert(farm.ploughAt(farmland.x,farmland.z,farmland.topY));
assert(!farm.ploughAt(farmland.x,farmland.z,farmland.topY));
assert(farm.seedAt(farmland.x,farmland.z,farmland.topY,0,'wheat'));
farm.animate(100,0); // crop growth uses normal Farm systems
assert(farmland.ploughed&&farmland.crop);
const runtime=createArchipelagoRuntime(farm);
const world=runtime.persistentState(100);
const state={schemaVersion:0,world,buildings:[],vehicles:[],activeVehicleId:'test',progression:{},ui:{},environment:{phase:.4}};
assert(validState(state),'expanded topology accepted by validator');
const physics2=await createPhysics();
const restored=generateFarm(new THREE.Scene(),physics2,world.seed,0,()=>{}, {attachmentComplete:true,savedWorld:world});
restored.restorePersistentState(world,100);
assert.equal(restored.terrain.size,farm.terrain.size);
assert(restored.terrain.get(gridKey(farmland.gx,farmland.gz)).ploughed);
assert.equal(restored.connections.length,farm.connections.length);
console.log('PASS farming, unique ploughing, expanded topology + crops restore');
physics.placeVehicle('test',{x:0,y:0,z:Math.max(...[...farm.terrain.values()].map(t=>t.z))},true);
farm.attachments.select(incoming);assert(farm.attachments.release());
assert.equal(farm.terrain.size,initialTiles);
assert.equal(physics.staticColliders.length,initialColliders);
assert(incoming.group.parent);
assert.equal(incoming.body.numColliders(),0);
assert.equal(incoming.status,'releasing');
const releaseStart=incoming.group.position.clone();
for(let i=0;i<120;i++){farm.driftingIslands.update(1/60,{speed:1.15});physics.step(1/60);}
assert(incoming.group.position.distanceTo(releaseStart)>1);
assert.equal(farm.cropStats().planted,0);
console.log('PASS release removes playable topology/collision and visibly drifts existing island away');
const square=(id,cx,cz,r)=>new Map(Array.from({length:(r*2+1)**2},(_,i)=>{const gx=cx+i%(r*2+1)-r,gz=cz+Math.floor(i/(r*2+1))-r;return [gridKey(gx,gz),{gx,gz,x:gx,z:gz,topY:0,islandId:id}];}));
const bay=new Map([...square('island-0',-9,0,2),...square('island-1',9,0,2),...square('back',0,-9,2)]);
const filling=findAttachmentPlacement(square('incoming',0,0,2),bay);
assert.equal(filling.gaps.length,3,'bay filling should beat simple outer edge');
assert(Math.abs(filling.gx)<2&&Math.abs(filling.gz)<2);
console.log('PASS compact bay filling connects to three neighbors',filling.gx,filling.gz);
const {createAttachmentRoutePlanner,routeLength,positionOnRoute}=await import('../../src/world/islands/attachment-route.js');
const obstacle=square('persistent',0,0,5), traveler=square('incoming',0,0,2);
assert.equal(createAttachmentRoutePlanner(traveler,obstacle,[],{x:-15,z:0})({gx:15,gz:0,x:15,z:0}),null,'blocked pulls must not detour around land');
const direct=createAttachmentRoutePlanner(traveler,obstacle,[],{x:-15,z:0})({gx:-10,gz:0,x:-10,z:0});
assert(direct&&direct.length===2);
const bridge=[{x:0,z:0,width:2,depth:20}];
assert.equal(createAttachmentRoutePlanner(traveler,new Map(),bridge,{x:-15,z:0})({gx:15,gz:0,x:15,z:0}),null,'cannot pull through bridges');
console.log('PASS direct approaches accepted; land and bridge obstructions rejected without detours');
const routePhysics=await createPhysics();
const routeFarm=generateFarm(new THREE.Scene(),routePhysics,99173,0,()=>{}, {attachmentComplete:true});
const routed=generateIsland(12345,{radius:7});
routed.group.position.set(0,0,Math.max(...[...routeFarm.terrain.values()].map(t=>t.z))-Math.min(...[...routed.terrain.values()].map(t=>t.z))+6.5);
routed.status='drifting';routed.body=routePhysics.addMovingIsland(routed,routed.group.position,false);
routeFarm.group.add(routed.group);routeFarm.driftingIslands.active.push(routed);
const planner=createAttachmentRoutePlanner(routed.terrain,routeFarm.terrain,[],routed.group.position);
const nearest=findAttachmentPlacement(routed.terrain,routeFarm.terrain,[],undefined,planner);
const remote=findAttachmentPlacement(routed.terrain,routeFarm.terrain);
assert(nearest.route.length===2,'only direct pulls are offered');
assert(nearest.approachDistance<15,'prefer nearby approach');
console.log('PASS nearby direct approach selected',nearest.approachDistance);
routePhysics.createVehicle('test',{x:0,y:0,z:Math.max(...[...routeFarm.terrain.values()].map(t=>t.z))});
routeFarm.attachments.select(routed);assert(routeFarm.attachments.connect());
assert.equal(routeFarm.attachments.pendingState().placement.route.length,2);
const originalGround=[...routeFarm.terrain.values()];
for(let frame=0;frame<3600&&routed.status!=='attached';frame++){
 routeFarm.attachments.update(1/60);
 for(const tile of routed.terrain.values())for(const solid of originalGround)assert(Math.abs(tile.x+routed.group.position.x-solid.x)>=1||Math.abs(tile.z+routed.group.position.z-solid.z)>=1,'actual animation may not cross persistent terrain');
}
assert.equal(routed.status,'attached');
console.log('PASS every animation frame clears persistent terrain while pulling directly to the near side');
// Return the released, farmed island to a selectable passing pose, preserving its content.
physics.removeMovingIsland(incoming.body);
incoming.group.position.set(0,0,Math.max(...[...farm.terrain.values()].map(t=>t.z))-Math.min(...[...incoming.terrain.values()].map(t=>t.z))+6.5);incoming.status='drifting';
incoming.body=physics.addMovingIsland(incoming,incoming.group.position,false);
physics.placeVehicle('test',{x:0,y:0,z:Math.max(...[...farm.terrain.values()].map(t=>t.z))},true);
farm.attachments.select(incoming);assert(farm.attachments.connect());
for(let i=0;i<600&&incoming.status!=='attached';i++)farm.attachments.update(.1);
assert.equal(incoming.status,'attached');
assert([...incoming.worldTiles.values()].some(t=>t.ploughed&&t.crop));
console.log('PASS released farming state survives reconnection at the chosen new pose');
const bayDirect=findAttachmentPlacement(square('incoming',0,0,2),bay,[],undefined,createAttachmentRoutePlanner(square('incoming',0,0,2),bay,[],{x:0,z:14}));
assert.equal(bayDirect.gaps.length,3,'directly reachable bays still win over a simple edge');
console.log('PASS direct approach preserves the strong three-neighbor bay preference');
